### PR TITLE
bump to 2.9.2-linux1

### PR DESCRIPTION
**Pull request by shiftkey**

### CODE REVIEW

**Comment by shiftkey** [comment]
Looks like the Docker image we rely on is lacking a `glibc` update from last month which means we see various tools fail:

```
==> Starting build()...
402
node: /usr/lib/libc.so.6: version `GLIBC_2.33' not found (required by node)
```

The first failure from the automated rebuilds was on February 6 https://github.com/WhyNotHugo/docker-makepkg/commit/41450fd4a1569229e0fbac5d667df97388b26929 and I can't tell from the logs why that's failing on Docker's infrastructure.

**Comment by shiftkey** [comment]
I have a fix prepared for this upstreamed: https://github.com/WhyNotHugo/docker-makepkg/pull/13

**Comment by fanninpm** [comment]
@immackay are you available to take this on?

**Comment by shiftkey** [comment]
Closing this out as it seems to be no longer active. The [`github-desktop-bin`](https://aur.archlinux.org/packages/github-desktop-bin/) package seems to be up-to-date, and the [`github-desktop`](https://aur.archlinux.org/packages/github-desktop/) is stuck with a packaging issue that I've opened a PR to support: https://github.com/alerque/aur/pull/22

Thanks again @immackay for handling the maintenance of these packages!

**Pull request closed without merging**
